version: '3.7'
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3003:3003'
      - '4003:4003'
    depends_on:
      - mongo
  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
      - '27100:27018'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: none
